#!/bin/sh
#        |\      _,,,---,,_    
#        /,`.-'`'    -.  ;-;;,_ 
#       |,4-  ) )-,_..;\ (  `'-'
#      '---''(_/--'  `-'\_)     
#########################################
# This README can be the install script #
#########################################

# Obvious disclamer, read this file before running it."

# 1. Install basic graphical components
  sudo xbps-install xorg dbus seatd herbstluftwm picom pipewire vala-panel-appmenu appmenu-gtk3-module appmenu-registrar
  
# 2. Make sure essential services are running
  # sudo ln -s /etc/sv/<service> /var/service/
  
# 3. Install "nice to have" software (only if xtools installed)
  xi links-x11 xterm rofi mpv cmus vimb yt-dlp

# 4. Moving into place!
  # To make the rice work, i recommend running the commands listed below
  # echo "cp .config/xinitrc ~/.xinitrc"
  # echo "chmod +x .config/herbstluftwm/autostart"
