#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# keybindings {{{
# remove all existing keybindings
hc keyunbind --all

# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q spawn sysask
hc keybind $Mod-Shift-c close_or_remove
hc keybind $Mod-Return spawn xterm
hc keybind $Mod-c spawn rofi -show drun

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-i jumpto urgent

# }}}

# rules {{{
hc unrule -F
hc rule focus=on # normally focus new clients
hc set focus_follows_mouse 1
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class="Steam" floating=on
hc rule class~".*\.exe" floating=on
# }}}

hc set tree_style '╾│ ├└╼─┐'

# theme {{{
bg=$(xrdb -get background)
bg_alt=$(xrdb -get color0)
fg=$(xrdb -get foreground)
fg_alt=$(xrdb -get color15)
focus=$(xrdb -get color5)
urgent=$(xrdb -get color1)

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_normal_color "$bg"
hc set frame_border_active_color "$focus"
hc set frame_bg_normal_color "$bg_alt"
hc set frame_bg_active_color "$focus"
hc set frame_border_width 0
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_gap 4
hc set smart_frame_surroundings off

hc attr theme.background_color "$bg"
hc attr theme.normal.color "$bg"
hc attr theme.active.color "$focus"
hc attr theme.urgent.color "$urgent"
hc attr theme.border_width 0
hc attr theme.title_font "Iosevka Aile:size=10"
hc attr theme.title_color "$bg"
hc attr theme.normal.title_color "$fg"
hc attr theme.floating.title_height 15
hc attr theme.floating.title_depth 3
hc attr theme.floating.border_width 1

hc watch tags.focus.frame_count
hc -i attribute_changed tags.focus.frame_count | while read -r; do
    hc or / and , compare tags.focus.frame_count = 1 , set frame_transparent_width 0 / set frame_transparent_width 2
done &
# }}}

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
hc set auto_detect_monitors 1

pgrep -x pipewire || pipewire &
pgrep -x pipewire-pulse || pipewire-pulse &
dz_col &

{
    pids=( )
    # reserve some space
    hc pad 0 35
    # launch polybar
    vala-panel &
    pids+=( $! )
    # wait until the panels should be stopped
    herbstclient -w '(quit_panel|reload)'
    # stop all started panels
    kill "${pids[@]}"
}

# vim:foldmethod=marker
